version: 2

defaults: &defaults
  working_directory: ~/themur
  docker:
    - image: circleci/node:8.9.1
    
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Installing dependencies
          command: npm install
      - run:
          name: Build files
          command: npm run build
      
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/themur
          paths: .

  gh-pages-publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/themur
      - run:
          name: Deploy to gh-pages
          command: npm run deploy

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - gh-pages-publish:
          requires:
            - build
          filters:
            branches:
              only: master
        