version: 2

defaults: &defaults
  working_directory: ~/themur
  docker:
    - image: circleci/node:8.9.1
    
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Installing dependencies
          command: npm install
      - run:
          name: Build files
          command: npm run build
      - run:
          name: Alert
          command: echo "Built the dang files!"
      
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/themur
          paths: .